name: subscription_alert
description: A subscription tracking app with payment reminders.
publish_to: 'none'
version: 1.0.4+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Local Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

  # UI & Utils
  intl: ^0.20.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.3
  http: ^1.6.0
  share_plus: ^7.2.2
  simple_icons: ^14.6.1
  android_intent_plus: ^5.1.0

  # Home Screen Widget (Android)
  home_widget: ^0.6.0

  # Google Calendar API
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # PDF Generation
  pdf: ^3.11.1
  path_provider: ^2.1.3
  open_file: ^3.5.6

  # AdMob Ads
  google_mobile_ads: ^5.2.0
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/photo_2025-12-08_16-36-20.jpg"

flutter:
  uses-material-design: true
